---
title: "Untitled"
output: html_document
date: "2025-11-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(e1071)   
library(pROC)    
library(caret)   
library(ROSE)
library(dplyr)
library(smotefamily)
library(PRROC)
library(xgboost)
library(tidyr)
```
```{r}

results_nolag <- read.csv("C:\\Users\\railt\\DataScienceFanClub\\James\\results_nolag.csv")
results_lag1 <- read.csv("C:\\Users\\railt\\DataScienceFanClub\\James\\results_lag1.csv")
results_lag2 <- read.csv("C:\\Users\\railt\\DataScienceFanClub\\James\\results_lag2.csv")
results_lag3 <- read.csv("C:\\Users\\railt\\DataScienceFanClub\\James\\results_lag3.csv")

```


```{r}
ggplot(all_res, aes(x = factor(cost), y = gamma_lab, fill = AUC)) +
  geom_tile(color = "black") +
  geom_text(aes(label = sprintf("%.3f", AUC)), size = 3) +
  facet_wrap(~ lag) +
  labs(
    title = "SVM-RBF tuning: AUC by (cost, gamma)",
    x = "Cost (C)", y = "Gamma",
    fill = "AUC"
  ) +
  scale_fill_gradient(low = "white", high = "skyblue") +
  theme_minimal(base_size = 12)



```

```{r}
all_res_long <- all_res %>%
  pivot_longer(
    cols = c( AUC, Sensitivity, Specificity),
    names_to = "metric", values_to = "value"
  )

ggplot(all_res_long, aes(x = cost, y = value, color = gamma_lab, group = gamma_lab)) +
  geom_line() + geom_point() +
  facet_grid(metric ~ lag, scales = "free_y") +
  scale_x_log10(breaks = unique(all_res_long$cost)) +
  labs(
    title = "Tuning metrics by Cost and Gamma",
    x = "Cost (log scale)", y = "Metric value", color = "Gamma"
  ) +
  theme_minimal(base_size = 12)

```





```
