---
title: "XG Boost Optimised Models"
author: "Tomi"
date: "2025-11-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
library(xgboost)
library(dplyr)
library(pROC)
library(ggplot2)
library(caret)
```

```{r}
train_data <- read.csv("https://raw.githubusercontent.com/railtonjamesl-collab/DataScienceFanClub/refs/heads/main/Data/Val_traindata/df_train_val.csv")
test_data <- read.csv("https://raw.githubusercontent.com/railtonjamesl-collab/DataScienceFanClub/refs/heads/main/Data/Final_traindata/df_test.csv")
```

Features/label setup
```{r}
x <- paste0("X", 1:15)
base_features <- c(x, "X17", "X18")

lag_1yr_feats <- c(base_features, paste0(base_features, "_1yr"))
lag_2yr_feats <- c(lag_1yr_feats, paste0(base_features, "_2yr"))
lag_3yr_feats <- c(lag_2yr_feats, paste0(base_features, "_3yr"))

target <- "status_label_1yr"
```

The "best" parameters and features found
```{r}
features <- lag_2yr_feats

eta <- 0.1703463
gamma <- 1.207474
max_depth <- 3
min_child_weight <- 3
subsample <- 0.9568904
colsample_bytree <- 0.5001273

iter <- 18
```

Modelling with xgboost using the "best" parameters found from rolling windows cross-validation
```{r}
set.seed(347)

# Ensuring the labels are numeric
train_data[[target]] <- as.numeric(train_data[[target]] == "failed")
test_data[[target]] <- as.numeric(test_data[[target]] == "failed")

# Handling class imbalance
n_pos <- sum(train_data[[target]] == 1)
n_neg <- sum(train_data[[target]] == 0)
scale_pos_weight <- n_neg / n_pos

dtrain <- xgb.DMatrix(data = as.matrix(train_data[, features]), label = train_data[[target]])
dtest <- xgb.DMatrix(data = as.matrix(test_data[, features]), label = test_data[[target]])

params <- list(
  objective = "binary:logistic",
  eta = eta,
  gamma = gamma,
  max_depth = max_depth,
  min_child_weight = min_child_weight,
  subsample = subsample,
  colsample_bytree = colsample_bytree,
  eval_metric = "auc",
  scale_pos_weight = scale_pos_weight
)

xgb_model <- xgb.train(params = params, data = dtrain, nrounds = iter)
preds <- predict(xgb_model, dtest)
auc <- auc(test_data[[target]], preds)
```

Result
```{r}
print(paste0("AUC Score: ", auc))
```






Feature importance plot
```{r}
importance_matrix <- xgb.importance(feature_names = colnames(dtrain), model = xgb_model)
xgb.plot.importance(importance_matrix = importance_matrix)
```

```{r}
correlation_matrix <- cor(train_data[, features])

high_correlation <- which(abs(correlation_matrix) > 0.95 & abs(correlation_matrix) < 1, arr.ind = TRUE)

high_corr <- high_correlation[high_correlation[, 1] < high_correlation[, 2], ]
for (i in 1:nrow(high_corr)) {
  cat("Correlation between", colnames(train_data[, features])[high_corr[i, 1]], "and", colnames(train_data[, features])[high_corr[i, 2]], "=", correlation_matrix[high_corr[i, 1], high_corr[i, 2]], "\n")
}
```

```{r}
features1 <- c("X1", "X3", "X4", "X5", "X6", "X7", "X8", "X10", "X11", "X12", "X13", "X14", "X15", "X17", "X18")
features1_1yr_lag <- c(features1, paste0(features1, "_1yr"))
features <- c(features1_1yr_lag, paste0(features1, "_2yr"))


dtrain <- xgb.DMatrix(data = as.matrix(train_data[, features]), label = train_data[[target]])
dtest1 <- xgb.DMatrix(data = as.matrix(test_data[, features]), label = test_data[[target]])

xgb_model_1 <- xgb.train(params = params, data = dtrain, nrounds = iter)
```

```{r}
features2 <- c("X1", "X3", "X5", "X6", "X7", "X8", "X10", "X11", "X12", "X13", "X14", "X15", "X18")
features2_1yr_lag <- c(features2, paste0(features2, "_1yr"))
features <- c(features2_1yr_lag, paste0(features2, "_2yr"))


dtrain <- xgb.DMatrix(data = as.matrix(train_data[, features]), label = train_data[[target]])
dtest2 <- xgb.DMatrix(data = as.matrix(test_data[, features]), label = test_data[[target]])

xgb_model_2 <- xgb.train(params = params, data = dtrain, nrounds = iter)
```


```{r}
preds1 <- predict(xgb_model_1, dtest1)
preds2 <- predict(xgb_model_2, dtest2)

auc1 <- auc(test_data[[target]], preds1)
auc2 <- auc(test_data[[target]], preds2)

roc <- roc(test_data[[target]], preds)
roc1 <- roc(test_data[[target]], preds1)
roc2 <- roc(test_data[[target]], preds2)

# Visualising all the results
plot(roc, col = "black", main = "ROC curves with AUC scores")
plot(roc1, col = "blue", add = TRUE)
plot(roc2, col = "green", add = TRUE)
legend("bottomright", legend = c("Model0", "Model1", "Model2"), col = c("black", "blue", "green"), lwd = 2)

text(x = 0.6, y = 0.4, labels = round(auc, 3), col = "black")
text(x = 0.6, y = 0.2, labels = round(auc1, 3), col = "blue")
text(x = 0.7, y = 0.3, labels = round(auc2, 3), col = "green")
```
